default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: campaigns

test:
  <<: *default
  database: campaigns_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
